name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  eslint:
    name: run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Adzz/jest_test_action@v1.0.0
        with:
          package-manager: npm
          command: eslint
